server:
    listen-address: ":8098"
    # for unix domain:
    # listen-address: "unix:/path/to/sock"

    # comment these out for plaintext (if you're using a reverse proxy for TLS termination)
    tls:
        cert: "fullchain.pem"
        key:  "privkey.pem"

    paths:
        # POST upload endpoint
        upload: "/upload"
        # GET or HEAD endpoint to access uploaded files
        files: "/files"
        # to serve the files with nginx or similar:
        #files-url: "https://example.com/files"

directory: "/path/to/storage"

limits:
    expiration: 60d
    # max file size in bytes (0 or missing means no limit)
    # examples: 10485760 (10 MB), 104857600 (100 MB), 1073741824 (1 GB)
    max-file-size: 0


# Access-Control-Allow-Origin header to send for browser-based clients.
# needed for webirc if filehost domain differs from client host. 
cors-allowed-origins:
    # - "https://filehost.example.com"


# strip EXIF metadata from uploaded images (jpg, jpeg, avif, heif, heic)
# requires exiftool to be installed
strip-exif-metadata: false

ergo:
    api-url: "http://127.0.0.1:8089"
    bearer-token: "example"

# error, warn, info, debug
logging: debug
